### ISSUE TITLE
Step 16. Open the browser.

### ISSUE THREAD

**Issue by monavariyas** [aman4720/Superset#14]
Remove is  from 'This is the correct URL **is** 

difference between http and https

**Comment by aman4720** [comment]
HTTP (HyperText Transfer Protocol):
Not Secure: HTTP is a standard protocol used for transmitting data between a web browser and a website's server.
And
HTTPS (HyperText Transfer Protocol Secure):
Secure: HTTPS is a secure version of HTTP.
